# Generated by Django 3.0.1 on 2020-01-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_Title', models.CharField(max_length=50)),
                ('asset_Type', models.CharField(max_length=20)),
                ('asset_Price', models.IntegerField()),
                ('asset_purpose', models.CharField(max_length=10)),
                ('asset_Location', models.CharField(max_length=50)),
                ('asset_Image', models.ImageField(upload_to='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endUser.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_Date', models.DateTimeField()),
                ('booking_Status', models.BooleanField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.Asset')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endUser.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='AddToFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ManyToManyField(to='booking.Asset')),
                ('buyer', models.ManyToManyField(to='endUser.Buyer')),
            ],
        ),
    ]
