# Generated by Django 3.0.1 on 2020-02-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('asset_Title', models.CharField(max_length=50)),
                ('asset_Type', models.CharField(max_length=20)),
                ('asset_Price', models.IntegerField()),
                ('asset_purpose', models.CharField(max_length=10)),
                ('asset_Location', models.CharField(max_length=50)),
                ('asset_Image', models.FileField(null=True, upload_to='assets/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_Date', models.DateTimeField(auto_now_add=True)),
                ('booking_Status', models.BooleanField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
