# Generated by Django 3.0.1 on 2020-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_Status',
            field=models.BooleanField(choices=[('Available', 'Available'), ('Booked', 'Booked')]),
        ),
    ]
