# Generated by Django 3.0.1 on 2020-02-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_Image',
            field=models.FileField(default=True, null=True, upload_to='assets/'),
        ),
    ]
