# Generated by Django 3.0.1 on 2020-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_asset_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
