# Generated by Django 3.0.1 on 2020-02-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200207_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_Image',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
    ]
