# Generated by Django 3.0.1 on 2020-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_asset_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_Status',
            field=models.BooleanField(),
        ),
    ]
