# Generated by Django 3.0.1 on 2020-02-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200206_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToFav',
        ),
    ]
