# Generated by Django 3.0.1 on 2020-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_delete_addtofav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_favorite',
        ),
    ]
