# Generated by Django 2.2.7 on 2020-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_Name', models.CharField(max_length=30)),
                ('buyer_Contact', models.IntegerField()),
                ('buyer_Address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_Name', models.CharField(max_length=30)),
                ('seller_Contact', models.IntegerField()),
                ('seller_Address', models.CharField(max_length=40)),
            ],
        ),
    ]
