# Generated by Django 2.2.7 on 2020-01-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endUser', '0003_auto_20200116_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='EndUser',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.RenameField(
            model_name='enduser',
            old_name='buyer_Address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='enduser',
            old_name='buyer_Contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='enduser',
            old_name='buyer_Name',
            new_name='Name',
        ),
    ]
